- name: Run Python script and capture output or errors
      run: |
        output=$(python app.py 2>&1) || echo "SCRIPT_ERROR=true" >> $GITHUB_ENV
        echo "SCRIPT_OUTPUT<<EOF" >> $GITHUB_ENV
        echo "$output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create summary file
      run: |
        echo "## Python Script Results" > summary.md
        echo '```' >> summary.md
        if [[ "${{ env.SCRIPT_ERROR }}" == "true" ]]; then
          echo "Error occurred during script execution:" >> summary.md
        else
          echo "Script executed successfully. Output:" >> summary.md
        fi
        echo "${{ env.SCRIPT_OUTPUT }}" >> summary.md
        echo '```' >> summary.md

    - name: Upload summary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kosta
        path: summary.md

    - name: Add script output or error to job summary
      run: |
        echo "## Python Script Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        if [[ "${{ env.SCRIPT_ERROR }}" == "true" ]]; then
          echo "Error occurred during script execution:" >> $GITHUB_STEP_SUMMARY
        else
          echo "Script executed successfully. Output:" >> $GITHUB_STEP_SUMMARY
        fi
        echo "${{ env.SCRIPT_OUTPUT }}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Exit with error if script failed
      if: env.SCRIPT_ERROR == 'true'
      run: exit 1
