name: Run Python Script

on:
  push:
    branches:
      - main  # or any branch you want to trigger the action on

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      if: exists('requirements.txt')

    - name: Run Python script
      run: |
        output=$(python app.py)
        echo "SCRIPT_OUTPUT<<EOF" >> $GITHUB_ENV
        echo "$output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Add script output to job summary
      run: |
        echo "## Python Script Output" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "${{ env.SCRIPT_OUTPUT }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
