name: Run Python Script and Store Results
on:
  push:
    branches:
      - main  # or any branch you want to trigger the action on
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script and capture output or errors
      run: |
        output=$(python app.py 2>&1) || echo "SCRIPT_ERROR=true" >> $GITHUB_ENV
        echo "SCRIPT_OUTPUT<<EOF" >> $GITHUB_ENV
        echo "$output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create summary file
      run: |
        echo "## Python Script Results" > summary.md
        echo '```' >> summary.md
        if [ "${SCRIPT_ERROR}" = "true" ]; then
          echo "Error occurred during script execution:" >> summary.md
        else
          echo "Script executed successfully. Output:" >> summary.md
        fi
        echo "${{ env.SCRIPT_OUTPUT }}" >> summary.md
        echo '```' >> summary.md

    - name: Upload summary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kosta
        path: summary.md

    - name: Add script output or error to job summary
      run: |
        echo "## Python Script Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        if [ "${SCRIPT_ERROR}" = "true" ]; then
          echo "Error occurred during script execution:" >> $GITHUB_STEP_SUMMARY
        else
          echo "Script executed successfully. Output:" >> $GITHUB_STEP_SUMMARY
        fi
        echo "${{ env.SCRIPT_OUTPUT }}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Exit with error if script failed
      if: env.SCRIPT_ERROR == 'true'
      run: exit 1
